default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geosmara_development

test:
  <<: *default
  database: geosmara_test

production:
  <<: *default
  database: <%= ENV["PRODUCTION_DB_NAME"] %>
  username: <%= ENV["PRODUCTION_DB_USERNAME"] %>
  password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
  host: <%= ENV.fetch('PRODUCTION_DB_HOST') %>